server:
  port: 8767
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    service1:
      path: /service1/**
      serviceId: ribbon
    service2:
      path: /service2/**
      serviceId: feign-support